### ISSUE TITLE
Unminified version not available

### ISSUE THREAD

**Issue by pedzed** [CreativeDream/jquery.modal#3]
Is there any reason that the original unminified version is not available? It would be nice to be able to see the source without having to use tools like [unminify.com](http://unminify.com).

**Comment by CreativeDream** [comment]
i don't have this version anymore :disappointed:

**Comment by pedzed** [comment]
It is removed in https://github.com/CreativeDream/jquery.modal/commit/ff60dbd76c1b787cae2c62453aa1d01477f61807. I will create a pull request if you want, you can add it back. It's unminified using unminify.com (it's the latest version).

**Edit:** Added pull request https://github.com/CreativeDream/jquery.modal/pull/5
