### ISSUE TITLE
Font size doesn't get overwritten for paragraphs

### ISSUE THREAD

**Issue by pedzed** [CreativeDream/jquery.modal#6]
I am using Foundation and the font size doesn't get overwritten by _jquery.modal_ (using the Xenon theme), which makes it result in the following:

![font size gets overwritten in paragraph](https://i.imgur.com/qKAxujV.png)

As you can see, the font sizes are not consistent. This can be fixed by targeting the `p` element.

_Extra info: this is the code I am using:_

``` js
[
    'Teacher: ' + event.teacherName+ '<br />',
    'From: ' + moment(event.start).format('HH:mm') + '<br />',
    'To: ' + moment(event.end).format('HH:mm') + '<br />',
    'Location: ' + event.locationName + '<br />',
    '<p>',
        'Notes: ' + event.notes + '<br />',
    '</p>',
].join('');
```

**Comment by CreativeDream** [comment]
update it.

<a href="https://github.com/CreativeDream/jquery.modal/releases/tag/v1.2.2">v1.2.2</a>
